// Mapa do painel: 10 módulos e 73 telas. Os dados vêm de shared/pages.ts
// (usado também pelo servidor); aqui só se acrescentam os ícones.
import type { LucideIcon } from 'lucide-react'
import {
  Activity,
  ArrowDownToLine,
  ArrowLeftRight,
  ArrowUpFromLine,
  AtSign,
  Award,
  BadgePercent,
  Bell,
  Blocks,
  Bot,
  Braces,
  Building2,
  ChartColumnIncreasing,
  CircleUserRound,
  Coins,
  Construction,
  CreditCard,
  Earth,
  FileText,
  Gamepad2,
  GalleryHorizontalEnd,
  Gift,
  Globe,
  HandCoins,
  Headset,
  HeartHandshake,
  House,
  IdCard,
  Image,
  Inbox,
  KeyRound,
  Landmark,
  LayoutDashboard,
  LayoutGrid,
  LayoutList,
  Link2,
  LoaderPinwheel,
  Lock,
  Mail,
  Medal,
  Megaphone,
  Network,
  Palette,
  PanelBottom,
  PanelTop,
  Percent,
  PieChart,
  PiggyBank,
  Plug,
  Radar,
  Receipt,
  Repeat,
  Route,
  ScrollText,
  SearchCode,
  Send,
  Settings,
  ShieldAlert,
  Siren,
  SlidersHorizontal,
  Sparkles,
  Store,
  Swords,
  Target,
  TicketPercent,
  Trophy,
  TrendingUp,
  UserCog,
  UserPlus,
  Users,
  UsersRound,
  Volleyball,
  Wallet,
  Webhook,
  Shield,
} from 'lucide-react'
import { MODULE_INFO, PAGE_INFO, type ModuleId, type ModuleInfo, type PageInfo, type PageKind } from '@shared/pages'

export type { ModuleId, PageKind }

export interface PageDef extends PageInfo {
  icon: LucideIcon
}

export interface ModuleDef extends ModuleInfo {
  icon: LucideIcon
}

const MODULE_ICONS: Record<ModuleId, LucideIcon> = {
  geral: LayoutDashboard,
  operacao: Wallet,
  esportes: Volleyball,
  cassino: Gamepad2,
  crescimento: TrendingUp,
  afiliados: HandCoins,
  campanhas: Megaphone,
  personalizacao: Palette,
  seguranca: Shield,
  configuracoes: Settings,
}

const PAGE_ICONS: Record<string, LucideIcon> = {
  'dashboard': LayoutDashboard,
  'usuarios': Users,
  'rankings': Trophy,
  'transacoes': ArrowLeftRight,
  'saques': ArrowUpFromLine,
  'depositos': ArrowDownToLine,
  'apostas-esportivas': Volleyball,
  'jogos': Gamepad2,
  'provedoras': Building2,
  'vitrines': LayoutGrid,
  'agregadores': Network,
  'ggr': ChartColumnIncreasing,
  'ranking-afiliados': Medal,
  'indicados': UserPlus,
  'links': Link2,
  'comissoes': Percent,
  'afiliados-visao-geral': PieChart,
  'afiliados-gerentes': UserCog,
  'afiliados-saques': HandCoins,
  'afiliados-configuracao': SlidersHorizontal,
  'promocoes': Megaphone,
  'templates': Braces,
  'webhooks': Webhook,
  'free-spins': Sparkles,
  'bonus-deposito': Gift,
  'saldo-bonus': PiggyBank,
  'rollover': Repeat,
  'moeda': Coins,
  'roleta': LoaderPinwheel,
  'loja': Store,
  'cupons': TicketPercent,
  'indicacao': UsersRound,
  'missoes': Target,
  'torneios': Swords,
  'niveis': Award,
  'cashback': BadgePercent,
  'notificacoes': Bell,
  'popups-inbox': Inbox,
  'disparos': Send,
  'jornadas': Route,
  'estatisticas': Activity,
  'tema': Palette,
  'sportsbook': Trophy,
  'home': House,
  'provedores-home': LayoutList,
  'banners': Image,
  'avatares': CircleUserRound,
  'menus': PanelTop,
  'carrosseis': GalleryHorizontalEnd,
  'rodape': PanelBottom,
  'redes-sociais': AtSign,
  'seo': SearchCode,
  'antifraude': ShieldAlert,
  'modo-ataque': Siren,
  'empresa': Landmark,
  'faturas': Receipt,
  'textos-legais': FileText,
  'modulos': Blocks,
  'cadastro': IdCard,
  'jogo-responsavel': HeartHandshake,
  'suporte': Headset,
  'manutencao': Construction,
  'dominios': Globe,
  'paises': Earth,
  'tracking': Radar,
  'gateways': CreditCard,
  'integracoes': Plug,
  'templates-email': Mail,
  'equipe': UsersRound,
  'cargos': KeyRound,
  'mcp': Bot,
  'seguranca-painel': Lock,
  'auditoria': ScrollText,
}

export const MODULES: ModuleDef[] = MODULE_INFO.map((m) => ({ ...m, icon: MODULE_ICONS[m.id] }))

export const PAGES: PageDef[] = PAGE_INFO.map((pg) => ({ ...pg, icon: PAGE_ICONS[pg.id] }))

export const PAGE_BY_ID = new Map(PAGES.map((pg) => [pg.id, pg]))
export const MODULE_BY_ID = new Map(MODULES.map((m) => [m.id, m]))

export function pagesOf(module: ModuleId) {
  return PAGES.filter((pg) => pg.module === module)
}

export function pageByPath(path: string) {
  return PAGES.find((pg) => pg.path === path)
}
